config/routes.rb
Rails.application.routes.draw do
  get 'top/index'

  root 'top#index'
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :articles do
    resources :talks, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  get "tweet/input"
  post "tweet/update"
  resources :users, only: [:show]
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :article, counter_cache: :likes_count

   validates :user, presence: true
   validates :user_id, uniqueness: { scope: :article_id }
   validates :article, presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, article_id: params[:article_id])
    @likes = Like.where(article_id: params[:article_id])
    @articles = Article.all
    @article  = Article.find(params[:article_id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, article_id: params[:article_id])
    like.destroy
    @likes = Like.where(article_id: params[:article_id])
    @articles = Article.all
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if article.like_user(current_user.id) %>
  <% else %>
    <%= button_to "", article_likes_path( :article_id => article.id ), :method => :post, id: "like-button-#{article.id}", remote: true %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$("#like-buttons").html("<%= j(render partial: 'likes/like', locals: { article: @article, likes: @likes, like: @like}) %>");

app/views/likes/destroy.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { article: @article, likes: @likes }) %>");